<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>9458fbcd-fc09-45bc-a5b3-dfea3a528b3b</UserSecretsId>
		<DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<_ContentIncludedByDefault Remove="appsettings.json" />
		<_ContentIncludedByDefault Remove="wwwroot\firebase.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.18.1" />
		<PackageReference Include="Serilog" Version="3.1.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EasyWayRide.Services\EasyWayRide.Services.csproj" />
		<ProjectReference Include="..\EasyWayRide.Shared\EasyWayRide.Shared.csproj" />
	</ItemGroup>
</Project>
