<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Validators\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="CorePush" Version="4.1.0" />
		<PackageReference Include="FirebaseAdmin" Version="2.4.0" />
		<PackageReference Include="GoogleApi" Version="5.2.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NRedisStack" Version="0.9.0" />
		<PackageReference Include="RabbitMQ.Client" Version="6.6.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EasyWayRide.DataAccess\EasyWayRide.DataAccess.csproj" />
		<ProjectReference Include="..\EasyWayRide.Shared\EasyWayRide.Shared.csproj" />
	</ItemGroup>

</Project>
