<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CoordinateSharp" Version="2.20.1.1" />
		<PackageReference Include="CorePush" Version="4.1.0" />
		<PackageReference Include="Dapper" Version="2.1.4" />
		<PackageReference Include="GeoJSON.Net" Version="1.2.19" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.11" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="7.0.11" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Core" Version="7.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="7.0.10" />
		<PackageReference Include="NRedisStack" Version="0.9.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
		<PackageReference Include="System.Linq.Async" Version="6.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EasyWayRide.Shared\EasyWayRide.Shared.csproj" />
	</ItemGroup>

</Project>
